import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Stream } from "@cloudflare/stream-react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stream controls autoplay width="1920" height="1080" src="918556ff7a08ff3d08a2c01f93018996" />
    </div>
  )
}
